blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ GitHub Discussions
    url: https://github.com/ScratchAddons/ScratchAddons/discussions
    about: Ask a question, or just discuss about Scratch Addons on our GitHub Discussions (our own forums)
  - name: ğŸ“ Send feedback
    url: https://scratchaddons.com/feedback
    about: Send a general feedback on our website
  - name: ğŸ  Community Discord
    url: https://discord.gg/R5NBqwMjNc
    about: Discuss about Scratch Addons on our community Discord server (recommended)
  - name: ğŸ”§ Development Discord
    url: https://discord.gg/Ak8sCDQ
    about: Discuss about Scratch Addons on our development Discord server